### ISSUE TITLE
Revision_id_sequence is not getting created

### ISSUE THREAD

**Issue by amitblues123** [simplethings/EntityAudit#108] opened 2014-12-29 08:57 UTC
![selection_018](https://cloud.githubusercontent.com/assets/6374897/5567416/681d2228-8f6a-11e4-8891-312297a81197.png)
When we upgraded our application, we are getting the REVISIONS_ID_SEQ is not created and we check the database REVISIONS_SEQ is getting created instead of REVISIONS_ID_SEQ.

After that when we modify the code 
$sequenceName = $this->platform->supportsSequences()
                ? 'REVISIONS_ID_SEQ'
                : null;
to
$sequenceName = $this->platform->supportsSequences()
                ? 'REVISIONS_SEQ'
                : null;

Then application is working fine. Please can anyone help me out we are using Oracle as database.

**Comment by andrewtch** [comment] 2015-01-29 15:36
Can you please provide test case or a PR? We currently lack an oracle test suite.

**Comment by dbykadorov** [comment] 2015-01-29 15:50
I have the similar issue with PostgreSQL with EntityAudit 0.7: 

```
{
    "require": {
        ...
        "simplethings/entity-audit-bundle": "0.*@dev",
    }
    ...
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

```
simple_things_entity_audit:
    table_prefix: "_entity_audit_"
    table_suffix: ""
    revision_table_name: _entity_audit_revision
```

By default schema tool want to creare entity_audit_revision_id_seq but the sequence name, as mentioned by @amitblues123, has been hardcoded in SimpleThings\EntityAudit\EventListener\LogRevisionsListener

https://github.com/simplethings/EntityAudit/blob/v0.7/src/SimpleThings/EntityAudit/EventListener/LogRevisionsListener.php#L174

Here my workarround (in Doctrine migration file):

```php
namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

class Version20150129171941 extends AbstractMigration
{
    /**
     * Migrate up
     *
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // ...
        $this->addSql(
            "CREATE TABLE _entity_audit_revision (
                id INT NOT NULL default nextval('revisions_id_seq'),
                timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                username VARCHAR(255) NOT NULL,
                PRIMARY KEY(id)
            )"
        );
        $this->addSql(
            "ALTER SEQUENCE revisions_id_seq OWNED BY _entity_audit_revision.id;"
        );
    }
```

I can't test it in master version because of "prefer-stable: true" option in my composer.json - looks like the code of this listener has been deeply refactored - and this bug might be fixed.

**Comment by andrewtch** [comment] 2015-01-29 16:17
(lucky guess) can you try:

```php
$sequenceName = $this->platform->supportsSequences()
                ? $this->platform->getIdentitySequenceName($this->config->getRevisionTableName(), 'id')
                : null;
```

for pg / oracle?

**Comment by dbykadorov** [comment] 2015-01-29 17:09
Looks like this works for postgres!

```php
$sequenceName = $this->platform->supportsSequences()
    ? $this->platform->getIdentitySequenceName($this->config->getRevisionTableName(), 'id')
    : null;
var_dump($sequenceName);die;

string '_entity_audit_revision_id_seq' (length=29)
```

Can you apply it to master and at least 0.7?

**Comment by andrewtch** [comment] 2015-01-29 17:15
let's wait for @amitblues123 to confirm.

**Comment by andrewtch** [comment] 2015-02-02 13:03
@amitblues123 , @dbykadorov , please check #119 by altering your composer.json as below:

```json
"require": {
    "simplethings/entity-audit-bundle": "dev-revision_sequence_name"
},
"repositories": [
    {
        "type": "git",
        "url":  "https://github.com/SiteSupra/EntityAudit.git"
    }
]
```

**Comment by dbykadorov** [comment] 2015-02-03 14:41
I migrated down from my workaround solution, changed my composer.json as you mentioned, and then I run composer update:

```bash
$ composer update -o simplethings/entity-audit-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing simplethings/entity-audit-bundle (v0.7)
  - Installing simplethings/entity-audit-bundle (dev-revision_sequence_name 912303e)
    Cloning 912303e7e35d4b901522e2acee797ca5fbe13865
```
Then I update my schema with default settings (with _entity_audit_revision_id_seq)
```
$ php app\console doctrine:schema:update --force
Updating database schema...
Database schema updated successfully! "12" queries were executed
```

... and looks like it works fine now: http://joxi.ru/BA04O15SV8jyAy

New revision and updated record has been created successfully.

**Comment by andrewtch** [comment] 2015-02-03 14:49
So, we can merge / close?

**Comment by dbykadorov** [comment] 2015-02-03 15:24
I see no errors with sequence now (postgresql). I think you can merge it now, but oracle issue still not confirmed.

**Comment by andrewtch** [comment] 2015-02-03 15:26
Well, they are basically the same. Closed by #119

**Closed by andrewtch** 2015-02-03 15:26 UTC
Labels: bug

**Comment by dbykadorov** [comment] 2015-02-03 17:39
@andrewtch does this fix only available in master? I can't use master because my composer.json have this option: "prefer-stable": true

**Comment by andrewtch** [comment] 2015-02-03 17:52
Quite probably we'll tag a release a bit later. Maybe you should use
particular hash or @dev?

**Comment by DavidBadura** [comment] 2015-02-03 20:48
you can use it with following configuration:

```json
"require": {
  "simplethings/entity-audit-bundle": "dev-master"
}
```

**Comment by dbykadorov** [comment] 2015-02-04 05:59
Okay! Thanks for your work on the bunlde!
